import type { Metadata } from "next";
// import * as stylex from "@stylexjs/stylex";
// import AuthProvider from "./context/authProvider";
import "./homeLayout.scss";
import { ReactQueryClientProvider } from "./queryClient";
import Navbar from "@/Components/Navbar/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return await (
    <ReactQueryClientProvider>
      <html className="html" lang="en">
        <body className="body">
          <>
            <Navbar />
            {children}
          </>
        </body>
      </html>
    </ReactQueryClientProvider>
  );
}
