import type { Metadata } from "next";
import * as stylex from "@stylexjs/stylex";
import Navbar from "@/Components/Navbar/navbar";
// import AuthProvider from "./context/authProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return await (
    <html {...stylex.props(styles.html)} lang="en">
      <body {...stylex.props(styles.body)}>
        {/* <AuthProvider> */}
          <div {...stylex.props(styles.nav)}>
            <Navbar />
          </div>
          <div id="portal"></div>
          {children}
        {/* </AuthProvider> */}
      </body>
    </html>
  );
}

// const DARK = "@media (prefers-color-scheme: dark)";
// const fgColor = `rgba(${$.foregroundR}, ${$.foregroundG}, ${$.foregroundB}, 1)`;

const styles = stylex.create({
  html: {
    margin: 0,
    padding: 0,
    width: "100%",
    // display: "flex",
    // justifyContent: "center",
    "font-family": "'Roboto', sans-serif",
  },
  body: {
    background: "white",
  },
  nav: {
    // display: {
    //   default: "visible",
    //   "@media (max-width: 500px)": "none",
    // }
    position: "absolute",
    top: 0,
    left: 0,
  },
});
