import type { Metadata } from "next";
// import * as stylex from "@stylexjs/stylex";
import Navbar from "@/Components/Navbar/navbar";
// import AuthProvider from "./context/authProvider";
import "./homeLayout.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return await (
    <html className="html" lang="en">
      <body className="body">
        {/* <AuthProvider> */}
        {/* <div {...stylex.props(styles.nav)}> */}
        <Navbar />
        {/* </div> */}
        {/* <div id="portal"></div> */}
        {children}
        {/* </AuthProvider> */}
      </body>
    </html>
  );
}
