"use server";
import { getServerSession } from "next-auth";
import { FC } from "react";
import { options } from "../api/auth/[...nextauth]/options";
import { redirect } from "next/navigation";
import SingnupSection from "./signupSection";
import { formData } from "../type";

const SignUp: FC = async () => {
  const session: any = await getServerSession(options);
  if (!session || !session?.user?.name) {
    return redirect("/"); // need to update this to profile page
  }
  const formData: formData = {
    name: {
      required: true,
      label: "Name",
      key: "name",
      value: session?.user?.name || "",
      disabled: !!session?.user?.name,
      type: "input",
      invalid: false,
      validationArray: [{ method: "length", value: [2, 20] }],
      // validation: [(value: string) => value.length > 2 && value.length < 20],
      message: "Please provide valid name.",
    },
    phone: {
      label: "Phone (+91)",
      key: "phone",
      value: "",
      type: "input",
      required: true,
      invalid: false,
      validationArray: [{ method: "length", value: 10 }],
      // validation: [(value: string) => value.length === 10],
      message: "Please provide valid 10 digit phone number.",
    },
    email: {
      required: true,
      label: "Name",
      key: "name",
      value: session?.user?.email || "",
      disabled: !!session?.user?.email,
      type: "input",
      invalid: false,
      validationArray: [
        { method: "length", value: [2, 20] },
        { method: "includes", value: "@" },
      ],
      // validation: [(value: string) => value.length > 2 && value.length < 20 && value.includes("@")],
      message: "Please provide valid name.",
    },
    house: {
      required: true,
      label: "House, Building, Company",
      key: "house",
      value: "",
      type: "input",
      invalid: false,
      validationArray: [{ method: "length", value: [2, 30] }],
      // validation: [(value: string) => value.length > 2 && value.length < 30],
      message: "Invalid Entry",
    },
    landmark: {
      type: "input",
      label: "Landmark",
      key: "landmark",
      value: "",
      required: true,
      invalid: false,
      validationArray: [{ method: "length", value: [2, 30] }],
      // validation: [(value: string) => value.length > 2 && value.length < 30],
      message: "Invalid Entry",
    },
    city: {
      type: "dropDown",
      dropDownValues: [
        "Adoor",
        "Alappuzha (Alleppey)",
        "Aluva",
        "Angamaly",
        "Attingal",
        "Calicut (Kozhikode)",
        "Changanassery",
        "Chavakkad",
        "Chengannur",
        "Cherthala",
        "Cherthala",
        "Cheruthuruthi",
        "Chittur-Thathamangalam",
        "Ernakulam",
        "Guruvayoor",
        "Idukki",
        "Irinjalakuda",
        "Kanhangad",
        "Kannur",
        "Kasaragod",
        "Kayamkulam",
        "Kochi (Cochin)",
        "Kollam (Quilon)",
        "Koothuparamba",
        "Kottarakkara",
        "Kottayam",
        "Kozhikode (Calicut)",
        "Kunnamkulam",
        "Kuthuparamba",
        "Malappuram",
        "Mananthavady",
        "Manjeri",
        "Mannarkkad",
        "Mattanur",
        "Mavelikara",
        "Muvattupuzha",
        "Nedumangad",
        "Nedumbassery",
        "Neyyattinkara",
        "Nilambur",
        "North Paravur",
        "Ottappalam",
        "Palakkad (Palghat)",
        "Pandalam",
        "Pathanamthitta",
        "Payyannur",
        "Perinthalmanna",
        "Perumbavoor",
        "Ponnani",
        "Punalur",
        "Shoranur",
        "Taliparamba",
        "Thalassery",
        "Thiruvalla",
        "Thiruvananthapuram (Trivandrum)",
        "Thiruvankulam",
        "Thodupuzha",
        "Thrissur",
        "Tirur",
        "Tiruvalla",
        "Tiruvananthapuram (Trivandrum)",
        "Tiruvannamalai",
        "Tiruvattur",
        "Tiruvottiyur",
        "Vaikom",
        "Varkala",
        "Vatakara",
      ],
      required: true,
      label: "City",
      key: "city",
      value: "",
      disabled: false,
      invalid: false,
      validationArray: [{ method: "dropDown" }],
      // validation: [
      //   (value: string) => {
      //     const rr = !!(
      //       value &&
      //       [
      //         "Adoor",
      //         "Alappuzha (Alleppey)",
      //         "Aluva",
      //         "Angamaly",
      //         "Attingal",
      //         "Calicut (Kozhikode)",
      //         "Changanassery",
      //         "Chavakkad",
      //         "Chengannur",
      //         "Cherthala",
      //         "Cherthala",
      //         "Cheruthuruthi",
      //         "Chittur-Thathamangalam",
      //         "Ernakulam",
      //         "Guruvayoor",
      //         "Idukki",
      //         "Irinjalakuda",
      //         "Kanhangad",
      //         "Kannur",
      //         "Kasaragod",
      //         "Kayamkulam",
      //         "Kochi (Cochin)",
      //         "Kollam (Quilon)",
      //         "Koothuparamba",
      //         "Kottarakkara",
      //         "Kottayam",
      //         "Kozhikode (Calicut)",
      //         "Kunnamkulam",
      //         "Kuthuparamba",
      //         "Malappuram",
      //         "Mananthavady",
      //         "Manjeri",
      //         "Mannarkkad",
      //         "Mattanur",
      //         "Mavelikara",
      //         "Muvattupuzha",
      //         "Nedumangad",
      //         "Nedumbassery",
      //         "Neyyattinkara",
      //         "Nilambur",
      //         "North Paravur",
      //         "Ottappalam",
      //         "Palakkad (Palghat)",
      //         "Pandalam",
      //         "Pathanamthitta",
      //         "Payyannur",
      //         "Perinthalmanna",
      //         "Perumbavoor",
      //         "Ponnani",
      //         "Punalur",
      //         "Shoranur",
      //         "Taliparamba",
      //         "Thalassery",
      //         "Thiruvalla",
      //         "Thiruvananthapuram (Trivandrum)",
      //         "Thiruvankulam",
      //         "Thodupuzha",
      //         "Thrissur",
      //         "Tirur",
      //         "Tiruvalla",
      //         "Tiruvananthapuram (Trivandrum)",
      //         "Tiruvannamalai",
      //         "Tiruvattur",
      //         "Tiruvottiyur",
      //         "Vaikom",
      //         "Varkala",
      //         "Vatakara",
      //       ].find((txt) => txt === value)
      //     );
      //     return rr;
      //   },
      // ],
      message: "Invalid Entry",
    },
    state: {
      type: "input",
      label: "State",
      key: "state",
      value: "Kerala",
      required: false,
      invalid: false,
      disabled: true,
      validationArray: [{ method: "length", value: [2, 20] }],
      // validation: [(value: string) => value.length > 2 && value.length < 20],
      message: "Invalid Entry",
    },
    pincode: {
      type: "input",
      required: true,
      label: "Pincode",
      key: "pincode",
      value: "",
      invalid: false,
      validationArray: [{ method: "length", value: 6 }],
      // validation: [(value: string) => value.length === 6],
      message: "Please provide valid 6 digit pincode.",
    },
  };
  return (
    <>
      <SingnupSection formDataProp={{ ...formData }} />
    </>
  );
};

export default SignUp;
